name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude=G204 ./...

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -o tf-summarize

  demo-issue-20:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: go build -o tf-summarize

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Print tf-summarize version and help
        run: |
          ./tf-summarize -v
          ./tf-summarize -h

      - name: Terraform Init
        run: terraform init
        working-directory: ./example

      - name: Terraform Plan
        run: terraform plan -out=tfplan -refresh=false # -refresh=false is only for demo workflow
        working-directory: ./example

      - name: Demonstrate issue 20 (https://github.com/dineshba/tf-summarize/issues/20)
        run: |
          terraform show -json tfplan > tfplan.json
          ../tf-summarize tfplan.json
        working-directory: ./example
